package intellij.unison.language

import com.intellij.lang.{ASTNode, ParserDefinition, PsiParser}
import com.intellij.lexer.Lexer
import com.intellij.openapi.project.Project
import com.intellij.psi.{FileViewProvider, PsiElement, PsiFile}
import com.intellij.psi.tree.{IFileElementType, TokenSet}
import intellij.unison.{UnisonLanguage, UnisonLexerAdapter}
import intellij.unison.language.parser.UnisonParser
import intellij.unison.language.psi.UnisonTypes

final class UnisonParserDefinition
    extends ParserDefinition {

  // IntelliJ treats these tokens as skippable between grammar elements.
  // IMPORTANT for significant whitespace: do NOT include NEWLINE/INDENT/DEDENT here.
  override def getWhitespaceTokens: TokenSet = UnisonTokenSets.WHITESPACE

  override def createLexer(project: Project): Lexer = new UnisonLexerAdapter()

  override def createParser(project: Project): PsiParser = new UnisonParser()

  override def getFileNodeType: IFileElementType = UnisonParserDefinition.FILE

  override def getCommentTokens: TokenSet = UnisonTokenSets.COMMENTS

  override def getStringLiteralElements: TokenSet = UnisonTokenSets.STRING_LITERALS

  // Maps AST nodes created by the parser to PSI element implementations (generated by Grammar-Kit).
  override def createElement(node: ASTNode): PsiElement =
    UnisonTypes.Factory.createElement(node)

  override def createFile(viewProvider: FileViewProvider): PsiFile =
    new UnisonFile(viewProvider)
}

object UnisonParserDefinition {
  val FILE: IFileElementType = new IFileElementType(UnisonLanguage.INSTANCE)
}
